spec:
  template:
   # metadata:
    #  annotations:
     #   nginx.ingress.kubernetes.io/proxy-body-size: 30m
      #  nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
       # nginx.ingress.kubernetes.io/proxy-buffering: "on"
       # nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
       # nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 2048m
    spec:
      containers:
        - name: controller
          args:
            - /nginx-ingress-controller
            - --election-id=ingress-nginx-leader
            - --controller-class=k8s.io/ingress-nginx
            - --ingress-class=nginx
            - --configmap=$(POD_NAMESPACE)/ingress-nginx-controller
            - --validating-webhook=:8443
            - --validating-webhook-certificate=/usr/local/certificates/cert
            - --validating-webhook-key=/usr/local/certificates/key
            - --watch-ingress-without-class=true
            - --publish-status-address=localhost
            - --enable-ssl-passthrough
